site_name: ePiE Manual 

nav:
  - Home: index.md
  - MkDocs: MkDocs.md
  - Manual Purpose: purp_scope_manual.md
  - Theoretical Background: b_information.md
  - 'How to: The ePiE App': ePiE_web.md
  - 'How to: The ePiE R package': ePiE_R.md
  - Model Interpretation: interpretation.md
  - Glossary: glossary.md

theme:
  name: material
  logo: ../img/Premier_Logo.png
  features:
    - navigation.footer
    - content.footnote.tooltips
  
  palette:
    primary: white

markdown_extensions:
  - attr_list
  - footnotes

extra_css:
  - stylesheets/extra.css

plugins:
  - glightbox:

copyright: © Copyright 20XX PREMIER Consortium